## Data_loader and data sets 

### Dataset will take your data set and it will structure in a perticuler format that will be given to the model.


### Dataset has a specific format how to call it with the help of a class function. The standerd format is given below.

In [2]:
# Here we will define 3 functions 1st init the constructor where we initialize the variables.

# CustDat ---> Name of the class 
# torch.utils.data.Dataset ----> fix library 

class CustDat(torch.utils.data.Dataset):
    def __init__(self, df, var_1):
        # initialize the variables
        ....
        ....
        
# len will give the number of rows in the dataset.

    def __len__(self):
        # return the length of the dataset 
        return...
    
# get item will take each and every row and convert it to a format so that you can feed it to your neural network(Model).

    def __getitem__(self, idx):
        # return each tensor wrt the index idx 
        return ...


SyntaxError: invalid syntax (1846018653.py, line 6)

In [5]:
import numpy as np
import torch 
import torch.nn as nn
import pandas as pd
from sklearn.datasets import make_classification

In [9]:
X, Y = make_classification(n_samples = 2000, n_features = 10, n_informative = 8, n_classes =2, random_state = 1234)
X, Y

(array([[-0.22951134, -1.28486655, -1.03529083, ..., -0.88437624,
         -0.31200188, -0.17531851],
        [ 0.78397162, -8.42042118, -6.4500266 , ..., -4.89386705,
          1.48164292, -3.9907251 ],
        [-1.21508496, -0.16449479, -1.56549441, ...,  0.06566343,
          2.90958903,  0.1178769 ],
        ...,
        [-1.62400922,  2.6916193 , -1.20914198, ...,  0.73644272,
         -4.43333782,  0.29673543],
        [ 0.88222046,  2.08500059, -1.95358229, ...,  0.45077147,
          1.19496267,  2.56893869],
        [ 0.70462012, -1.30252083,  2.12350211, ...,  1.59723925,
          5.2594936 , -1.12237264]]),
 array([0, 0, 0, ..., 1, 0, 0]))

In [11]:
X = pd.DataFrame(X)
X

0         1         2         3         4         5         6  \
0    -0.229511 -1.284867 -1.035291  1.558939 -0.664283 -0.587712  0.286911   
1     0.783972 -8.420421 -6.450027 -1.357731  3.216398  2.277358  0.900431   
2    -1.215085 -0.164495 -1.565494  0.903494  0.292994  1.455418 -4.046064   
3    -4.327243  5.263402  3.149521 -4.101906  1.833046 -3.189375 -0.339469   
4     3.697831 -2.873489 -0.720934  2.541765  2.102532  2.790593 -1.795269   
...        ...       ...       ...       ...       ...       ...       ...   
1995 -0.003929 -3.763024 -0.105216  1.236162  0.259713  0.920605 -0.949792   
1996  0.622498 -0.259702 -3.146410 -0.255492 -0.931579  2.150363 -3.137205   
1997 -1.624009  2.691619 -1.209142 -2.581748  2.439387 -1.997896 -1.285824   
1998  0.882220  2.085001 -1.953582  1.826337 -2.154304 -0.392498 -3.731504   
1999  0.704620 -1.302521  2.123502  0.550289  0.063839  2.942484 -0.857016   

             7         8         9  
0    -0.884376 -0.312002 -0.175319  
1    -4.893867  1.481643 -3.990725  
2     0.065663  2.909589  0.117877  
3     0.666235 -7.029234 -1.035204  
4     4.109290  8.011738  1.285353  
...        ...       ...       ...  
1995 -0.085153  2.720104 -3.486621  
1996  1.943374 -0.206618 -3.441643  
1997  0.736443 -4.433338  0.296735  
1998  0.450771  1.194963  2.568939  
1999  1.597239  5.259494 -1.122373  

[2000 rows x 10 columns]

In [13]:
X.shape[0]

2000

### We know that torch does every operation in tensors not in numpy arrays.

In [52]:
type(X), type(Y)

(pandas.core.frame.DataFrame, numpy.ndarray)

## Fisrt we will look to the Dataset library.

In [69]:
# Now here we will define the class with the necessay above discussed functions. 

class CustData(torch.utils.data.Dataset):
# This class will take 2 values as input.

    def __init__(self, X, Y):
        self.X = X 
        self.Y = Y
    def __len__(self):
        return self.X.shape[0]

# here in this function if we provide the index as idx then it should return that item means that row. 

    def __getitem__(self, idx ):
#         x_values = self.X.iloc[idx].values
        x_values = self.X.iloc[idx].values
        y_values = self.Y[idx]
# convert data to a tensor as torch works only in tensors.
        x_values = torch.from_numpy(x_values)
        y_values = torch.tensor(y_values)

        return x_values, y_values
        

In [70]:
CustData(X,Y).__getitem__(2)

(tensor([-1.2151, -0.1645, -1.5655,  0.9035,  0.2930,  1.4554, -4.0461,  0.0657,
          2.9096,  0.1179], dtype=torch.float64),
 tensor(0))

In [71]:
CustData(X,Y).__len__()

2000

In [72]:
Y

array([0, 0, 0, ..., 1, 0, 0])

## Now we will look in to the DataLoader we use Dataloader it is a function that we use in order to merge all the columns and give you an entire batch, so it is used in making batches. 

## The standerd way is shown below.


### cd = CustDat(df, var1)    `it is the class we have already instantiated.` 
### dl - dataloader 
### dl = torch.utils.data.Dataloader (  
###                                                        cd, >  ` first parameter is class itself library we have already created`, 
###                                                        batch_size = 16 >  `second parameter is compulsory batch size can use 16`,
###                                                        shuffle = True > ` it means we will shuffle the orders`,
###                                                        num_workers = 2 > `Parallel processing that fetch the data mostly 2 look in `,
###                                                        pin_memory = False `Need to look it is False as we are not using GPU `, 
###                                                       #sampler = None ` like shuffle how you want to get idx`,
###                                                       #collate_fn = new_collate, `Need to look it up`
###                                                     )

In [80]:
cd = CustData(X, Y) # here we have passed our data set X, Y 

In [81]:
dl = torch.utils.data.DataLoader(cd, batch_size = 16, shuffle = True, num_workers = 2, pin_memory = False )

In [82]:
for data in dl:
    print(data[0].shape)
    break
    


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pavankumar/.pyenv/versions/3.8.10/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/pavankumar/.pyenv/versions/3.8.10/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'CustData' on <module '__main__' (built-in)>


KeyboardInterrupt: 